version: "3"
services:
  web:
    build: ./nano_planner
    command: mix phx.server
    environment:
      MIX_ENV: "dev"
      PORT: "4000"
      DB_HOST: db
    volumes:
      - ./nano_planner:/nano_planner
    ports:
      - "4000:4000"
    links:
      - db
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data